version: "3"

services:
  pact-postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pactuser
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pactpostgres

  pact-broker:
    image: pactfoundation/pact-broker:2.68.1.0
    ports:
      - "9292:9292"
    depends_on:
      - pact-postgres
    environment:
      PACT_BROKER_PORT: '9292'
      PACT_BROKER_DATABASE_URL: "postgres://pactuser:docker@930105e84c8a/pactpostgres"
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG

volumes:
  postgres-volume:
